<div>{{jsSidebar("JavaScript Guide")}} {{PreviousNext("Web/JavaScript/Guide/Grammar_and_types", "Web/JavaScript/Guide/Loops_and_iteration")}}</div>

<p class="summary">Javascript soporta un conjunto compacto de sentencias, específicamente para el manejo de flujo, que puedes usar para incorporar mayor interactividad a tus aplicaciones. Este capítulo provee una vista general de las mismas.</p>

<p>La <a href="/en-US/docs/Web/JavaScript/Reference/Statements">guía de referencia de Javascript</a> contiene detalles exhaustivos sobre las sentencias mencionadas en este capítulo. El punto y coma (<code>;</code>) se utiliza para separar sentencias en código Javascript.</p>

<p>Cualquier expresión en Javascript también es una sentencia. Puedes ver <a href="/en-US/docs/Web/JavaScript/Guide/Expressions_and_Operators">Expresiones y operadores</a> para más información sobre expresiones.</p>

<h2 id="Sentencia_de_bloque">Sentencia de bloque</h2>

<p>La sentencia de bloque es el tipo de sentencia más básico y se utiliza para agrupar sentencias. El bloque se delimita entre un par de llaves:</p>

<pre class="syntaxbox">{ 
  sentencia_1;
  sentencia_2;
  . 
  . 
  . 
  sentencia_n; 
}
</pre>

<h3 id="Ejemplo"><strong>Ejemplo</strong></h3>

<p>Los bloques de sentencias son comúnmente utilizados para sentencias de  control de flujo  (ej. <code>if</code>, <code>for</code>, <code>while</code>).</p>

<pre class="brush: js">while (x &lt; 10) {
  x++;
}
</pre>

<p>En este caso <code>{ x++; }</code> es el bloque de sentencias.</p>

<p><strong>Importante</strong>: Javascript <strong>no</strong> tiene ámbito a nivel bloque en versiones anteriores a ECMAScript 6. Las variables introducidas dentro de un bloque pertenecen a la función o script que lo contiene y el efecto de declararlas persiste más alla del bloque mismo. En otras palabras, los bloques no introducen un nuevo ámbito. Si bien los bloques "Standalone" son válidos no deberían ser utilizados en Javascript ya que no se comportan como los bloques de C o Java. Por ejemplo:</p>

<pre class="brush: js">var x = 1;
{
  var x = 2;
}
console.log(x); // imprime 2
</pre>

<p>Este código imprime el número 2  dado que la sentencia <code>var x</code> dentro del bloque está en el mismo ámbito que la sentencia <code>var x</code> definida antes del bloque. En C o Java el equivalente de este código imprimiría 1.</p>

<p>A partir de ECMAScript 6, se introduce el ámbito a nivel bloque utilizando <code>let</code> para declarar las variables. Ver la referencia {{jsxref("Statements/let", "let")}}  para más información.</p>

<h2 id="Sentencias_condicionales">Sentencias condicionales</h2>

<p>Una sentencia condicional es un conjunto de comandos que se ejecutan si una condición es verdadera. JavaScript soporta dos sentencias condicionales: <code>if...else</code> y <code>switch</code></p>

<h3 id="Sentencia_if...else"><code>Sentencia if...else</code></h3>

<p>Se utiliza la sentencia <code>if</code> para comprobar si la condición lógica es verdadera. Se utiliza la opción <code>else</code> para ejecutar un sentencia si la condición es falsa. A continuación se muestra un ejemplo de <code>if...else</code>:</p>

<pre class="syntaxbox">if (condición) {
    sentencia_1;
} else { 
    sentencia_2;
}</pre>

<p>Aquí la <code>condición</code> puede ser cualquier expresión que se evalúa a true o false. Consultar <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean#Description">Boolean</a> para una explicación de como se evalúa <code>true</code> y <code>false</code>. Si la condición es verdadera, se ejecuta <code>sentencia_1</code>; de lo contrario, se ejecuta <code>sentencia_2</code>. La <code>sentencia_1</code> y la <code>sentencia_2</code> pueden ser cualquier sentencia, incluyendo otras sentencias anidadas en <code>if</code>.</p>

<p>También puedes componer sentencias más complejas usando <code>else if </code>para tener múltiples condiciones, como se muestra a continuación:</p>

<pre class="syntaxbox">if (condición_1) {
  sentencia_1;
} else if (condición_2) {
  sentencia_2;
} else if (condición_n) {
  sentencia_n;
} else {
  ultima_sentencia;
} 
</pre>

<p>En el caso de condiciones múltiples solamente la primera condición lógica que evalúa a verdadero va a ser ejecutada. Para ejecutar múltiples sentencias, agruparlas dentro de sentencias de bloque (<code>{ ... }</code>) . En general, usar siempre sentencias de bloque es una buena práctica, sobre todo cuando se anidan sentencias <code style="font-style: normal;">if</code>:</p>

<pre class="syntaxbox">if (condición) {
  ejecutar_sentencia_1_si_condición_es_verdadera;
  ejecutar_sentencia_2_si_condición_es_verdadera;
} else {
  ejecutar_sentencia_3_si_condición_es_falsa;
  ejecutar_sentencia_4_si_condición_es_falsa;
}
</pre>

<div>Es aconsejable no usar asignación simple dentro de una expresión condicional porque dicha asignación puede ser confundida con el comparador de igualdad cuando se lee de pasada el código. Por ejemplo, no usar el siguiente código:</div>

<div> </div>

<pre class="example-bad brush: js">if (x = y) {
  /* sentencias aquí */
}
</pre>

<p>Si necesitas usar una asignación dentro de una expresión de condición, una práctica común es poner paréntesis adicionales alrededor de la asignación. Por ejemplo:</p>

<pre class="brush: js">if ((x = y)) {
  /* sentencias aquí */
}
</pre>

<h4 id="Valores_falsos">Valores falsos:</h4>

<p>Los siguientes valores se evalúan como falso (también conocidos como valores {{Glossary("Falsy")}}):</p>

<ul>
 <li><code>false</code></li>
 <li><code>undefined</code></li>
 <li><code>null</code></li>
 <li><code>0</code></li>
 <li><code>NaN</code></li>
 <li>la cadena vacía (<code>""</code>)</li>
</ul>

<p>El resto de valores, incluídos todos los objetos, son evaluados como verdadero cuando son pasados a una sentencia condicional.</p>

<p>No confundir los valores primitivos booleanos <code>true</code> y <code>false</code> con los valores true y false del objeto {{jsxref("Boolean")}}. Por ejemplo:</p>

<pre class="brush: js">var b = new Boolean(false);
if (b) // Esta condición se evalua a true
if (b == true) // Esta condición se evalua a false</pre>

<h4 id="Ejemplo_2"><strong>Ejemplo</strong></h4>

<p>En el siguiente ejemplo, la función <code>comprobarDatos</code> devuelve <code>true</code> si el número de caracteres en un objeto <code>Text</code> es tres; en otro caso, muestra una alerta y devuelve <code>false</code>.</p>

<pre class="bad-example brush: js">function comprobarDatos() {
  if (document.form1.threeChar.value.length == 3) {
    return true;
  } else {
    alert("Introduce exactamente tres caracteres. " +
    document.form1.threeChar.value + " no es válido.");
    return false;
  }
}
</pre>

<h3 id="switch"><code>switch</code></h3>

<p>Una sentencia <code>switch</code> permite a un programa evaluar una expresión e intentar igualar el valor de dicha expresión a una etiqueta de caso (<code>case</code>). Si se encuentra una coincidencia, el programa ejecuta la sentencia asociada. Una sentencia <code>switch</code> se describe como se muestra a continuación:</p>

<pre class="syntaxbox">switch (expresión) {
  case etiqueta_1:
    sentencias_1
    [break;]
  case etiqueta_2:
    sentencias_2
    [break;]
    ...
  default:
    sentencias_por_defecto
    [break;]
}
</pre>

<p>El programa primero busca una claúsula <code>case</code> con una etiqueta que coincida con el valor de la expresión y, entonces, transfiere el control a esa cláusula, ejecutando las sentencias asociadas a ella. Si no se encuentran etiquetas coincidentes, el programa busca la cláusula opcional <code>default</code> y, si se encuentra, transfiere el control a esa cláusula, ejecutando las sentencias asociadas. Si no se encuentra la cláusula <code>default</code>, el programa continúa su ejecución por la siguiente sentencia al final del <code>switch</code>. Por convención, la cláusula por defecto es la última cláusula, aunque no es necesario que sea así.</p>

<p>La sentencia opcional <code>break</code> asociada con cada cláusula <code>case</code> asegura que el programa finaliza la sentencia <code>switch</code> una vez que la sentencia asociada a la etiqueta coincidente es ejecutada y continúa la ejecución por las sentencias siguientes a la sentencia switch. Si se omite la sentencia <code>break</code>, el programa continúa su ejecución por la siguiente sentencia que haya en la sentencia <code>switch</code>.</p>

<h4 id="Ejemplo_3"><strong>Ejemplo</strong></h4>

<p>En el siguiente ejemplo, si <code>tipoFruta</code> se evalúa como "Plátanos", el programa iguala el valor con el caso "Plátanos" y ejecuta las sentencias asociadas. Cuando se encuentra la sentencia <code>break</code>, el programa termina el <code>switch</code> y ejecuta las sentencias que le siguen. Si la sentencia <code>break</code> fuese omitida, la sentencia para el caso "Cerezas" también sería ejecutada.</p>

<pre class="brush: js">switch (tipoFruta) {
  case "Naranjas":
    console.log("Naranjas cuestan 0,59€ el kilo.");
    break;
  case "Manzanas":
    console.log("Manzanas cuestan 0,32€ el kilo.");
    break;
  case "Plátanos":
    console.log("Plátanos cuestan 0,48€ el kilo.");
    break;
  case "Cerezas":
    console.log("Cerezas cuestan 3,00€ el kilo.");
    break;
  case "Mangos":
    console.log("Mangos cuestan 0,56€ el kilo.");
    break;
  case "Papayas":
    console.log("Mangos y papayas cuestan 2,79€ el kilo.");
    break;
  default:
   console.log("Disculpa, no tenemos el tipo de fruta " + tipoFruta + ".");
}
console.log("¿Te gustaría tomar algo?");</pre>

<h2 id="Sentencias_de_manejo_de_excepciones">Sentencias de manejo de excepciones</h2>

<p>Puedes lanzar excepciones usando la sentencia <code>throw</code> y manejarlas usando las sentencias <code>try...catch</code>.</p>

<ul>
 <li><a href="#throw_statement"><code>throw</code> statement</a></li>
 <li><a href="#try_catch_statement"><code>try...catch</code> statement</a></li>
</ul>

<h3 id="Tipos_de_excepciones">Tipos de excepciones</h3>

<p>Prácticamente cualquier objecto puede ser lanzado en JavaScript. Sin embargo, no todos los objetos lanzados son creados igual. Mientras que es bastante común para lanzar números o strings como errores, frecuentemente son más efectivos utilizar uno de los tipos de excepciones específicamente creados para este proposito:  </p>

<ul>
 <li><a href="https://developer.mozilla.org/es/docs/Web/JavaScript/Referencia/Objetos_globales#Objetos_fundamentales">Excepciones ECMAScript</a></li>
 <li>{{domxref("DOMException")}} and {{domxref("DOMError")}}</li>
</ul>

<h3 id="Sentencia_throw"><code>Sentencia throw</code> </h3>

<p>Utiliza la sentencia <code>throw</code>  para lanzar una excepción. Cuando lanzas un excepción, se especifica la expresión que contiene el valor para ser lanzado:</p>

<pre class="syntaxbox">throw expresión;
</pre>

<p>Puedes lanzar cualquier expresión, no solo expresiones de un tipo especifico. En el siguente código lanzamos varias excepciones de varios tipos: </p>

<pre class="brush: js">throw "Error2";   // Tipo string
throw 42;         // Tipo número
throw true;       // Tipo booleano
throw {toString: function() { return "¡Soy un objeto!"; } };
</pre>

<div class="note"><strong>Note:</strong> Puedes especificar un objeto cuando lanzas una excepción. A continuación, puedes hacer referencia a las propiedades del objeto en un bloque catch.</div>

<pre class="brush: js">// Crear un tipo de objeto UserException
function UserException (aviso){
  this.aviso=aviso;
  this.nombre="UserException";
}

// Convertimos la excepción a String cuando es utilizada como un String
// (E.j: Un error de consola)
UserException.prototype.toString = function () {
  return this.nombre + ': "' + this.aviso + '"';
}

// Crea una instancia del objeto y lo lanza 
throw new UserException("Value too high");</pre>

<h3 id="try...catch"><code>try...catch</code></h3>

<p>La sentencia <code>try...catch</code> marca un bloque de instrucciones a intentar que pueden causar alguna excepción, y declarar una o más respuestas en caso de que una excepción sea arrojada. Si una excepción es arrojada, la sentencia <code>try...catch</code> se encarga de atraparla.</p>

<p>La sentencia <code>try...catch</code> consiste en un bloque <code>try</code>, el cuál contiene una o más instrucciones, y ninguno o varios bloques <code>catch</code>, conteniendo sentencias que especifican que hacer si una excepción es arrojada en un bloque <code>try</code>. Se desea que las instrucciones dentro del bloque <code>try</code> se ejecuten con éxito, de caso contrario caerán en el bloque <code>catch</code> para ser controladas. Si alguna instrucción dentro del bloque <code>try</code> (o en una función llamada dentro del bloque <code>try</code>) arroja una excepción, el control pasa inmediatamente al bloque <code>catch</code>. Si ninguna excepción es arrojada en el bloque <code>try</code>, el bloque <code>catch</code> es ignorado. Por último se ejecuta el bloque <code>finally</code> luego de que los bloques <code>try</code> y <code>catch</code> hayan sido ejecutados pero antes de las instrucciones que se encuentren a continuación de la sentencia <code>try...catch</code>.</p>

<p>El siguiente ejemplo usa la sentencia <code>try...catch</code>. El ejemplo llama a una función que retorna el nombre de un mes desde un arreglo basado en un valor pasado como argumento a la función. Si el valor no corresponde con el número de un mes (entre 1 y 12), una excepción es arrojada con el valor "<code>InvalidMonthNo</code>" y las instrucciones en el bloque <code>catch</code> le asignarán a la variable <code>monthName</code> el valor de <code>unknown</code>.</p>

<pre class="brush: js">function getMonthName (mo) {
  mo = mo-1; // Ajusta el indice del arreglo para el arreglo de meses (1=Jan, 12=Dec)
  var months = ["Jan","Feb","Mar","Apr","May","Jun","Jul",
                "Aug","Sep","Oct","Nov","Dec"];
  if (months[mo] != null) {
    return months[mo];
  } else {
    throw "InvalidMonthNo"; //Arroja la palabra "InvalidMonthNo" al ocurrir una excepción
  }
}

try { // instrucciones a probar
  monthName = getMonthName(myMonth); // La función puede arrojar una excepción
}
catch (e) {
  monthName = "unknown";
  logMyErrors(e); // Pasa el objeto de la excepción a un manejador de errores
}
</pre>

<h4 id="The_catch_Block" name="The_catch_Block">El bloque <code>catch</code></h4>

<p>Un bloque <code>catch</code> es usado para manejar todas las excepciones que pueden ser generadas en el bloque <code>try</code>.</p>

<pre class="brush: js">catch (catchID) {
  instrucciones
}
</pre>

<p>El bloque <code>catch</code> especifica un identificador (<code>catchID</code> en la sintaxis anterior) que tiene el valor especificado por la sentencia <code>throw</code>; puedes usar este identificador para obtener información acerca de la excepción que fue arrojada. JavaScript crea este identificador cuando ha entrado en el bloque <code>catch</code>; el identificador dura mientras dure el bloque <code>catch</code>; después de que el bloque <code>catch</code> termine su ejecución, el identificador ya no estará disponible.</p>

<p>Por ejemplo, el siguiente código arroja una excepción. Cuando la excepción ocurre, el control es transferido al bloque <code>catch</code>.</p>

<pre class="brush: js">try {
  throw "myException" // genera una excepción
}
catch (e) {
  // instrucciones para manejar cualquier excepción generada
  logMyErrors(e) // Pasa el objeto de excepción a un manejador de errores
}
</pre>

<h4 id="El_bloque_finally">El bloque <code>finally</code></h4>

<p>El bloque finally contiene instrucciones para ejecutar luego de la ejecución del bloque <code>try </code>y el bloque <code>catch</code> pero antes de las instrucciones ubicadas luego de la sentencia <code>try...catch</code>. El bloque <code>finally</code> se ejecuta cuando se haya arrojado o no una excepción. Si una excepción es arrojada, las instrucciones en el bloque <code>finally</code> se ejecutan incluso si no existe un bloque <code>catch</code> que maneje la excepción.</p>

<p>Se puede usar el bloque <code>finally</code> para hacer que tu script falle con gracia cuando una excepción ocurre; por ejemplo, puedes tener la necesidad de liberar un recurso que tu script tiene ocupado. El siguiente ejemplo abre un archivo y luego ejecuta instrucciones que usan el archivo (JavaScript del lado del servidor permite acceder a archivos). Si una excepción es arrojada mientras el archivo está abierto, el bloque <code>finally</code> cierra el archivo antes de que el script falle.</p>

<pre class="brush: js">openMyFile();
try {
  writeMyFile(theData); // Esto puede arrojar un error
} catch(e) {  
  handleError(e); // Si ocurre un error es manejado
} finally {
  closeMyFile(); // Siempre cierra el recurso
}
</pre>

<p>Si el bloque <code>finally </code>retorna un valor, este valor se convierte en el valor de retorno de toda la sentencia <code>try-catch-finally,</code> independientemente de cualquier sentencia return en el bloque <code>try </code>y el bloque <code>catch</code>:</p>

<pre class="brush: js">function f() {
  try {
    console.log(0);
    throw "bogus";
  } catch(e) {
    console.log(1);
    return true; // Esta sentencia de retorno es suspendida
                 // hasta que el bloque finally esté completo
    console.log(2); // no alcanzable
  } finally {
    console.log(3);
    return false; // sobreescribe la sentencia de retorno anterior
    console.log(4); // no alcanzable
  }
  // "return false" es ejecutada ahora
  console.log(5); // no alcanzable
}
f(); // console 0, 1, 3; retorna false
</pre>

<p>Sobreescribiendo los valores retornados por el bloque <code>finally</code> también aplica a excepciones arrojadas o relanzadas dentro de un bloque <code>catch</code>:</p>

<pre class="brush: js">function f() {
  try {
    throw "bogus";
  } catch(e) {
    console.log('caught inner "bogus"');
    throw e; // Esta sentencia throw es suspendida hasta que
             // el bloque finally se termine de ejecutar
  } finally {
    return false; // Sobreescribe la sentencia throw anterior
  }
  // "return false" es ejecutado ahora
}

try {
  f();
} catch(e) {
  // Esta nunca es encontrada porque la sentencia throw dentro
  // del bloque catch es sobrescrita por la sentencia return
  // en el bloque finally
  console.log('caught outer "bogus"');
}

// SALIDA
// atrapado dentro de "bogus"</pre>

<h4 id="Nesting_try...catch_Statements" name="Nesting_try...catch_Statements">Sentencias <code>try...catch</code> anidadas</h4>

<p>Es posible anidar una o más sentencias <code>try...catch</code>. Si una sentencia <code>try...catch</code> interna no posee un bloque <code>catch</code>, la sentencia<code> try...catch</code> exterior verifica si el bloque exterior genera una coincidencia.</p>

<h3 id="Utilizando_objetos_de_Error">Utilizando objetos de <code>Error</code></h3>

<p>Dependiendo del tipo de error, es posible usar el 'name' (nombre) y el 'message' (mensaje) propiedades para obtener un mensaje más refinado. La propiedad 'name' provee la clase general del Error(por ejemplo, 'DOMException' or 'Error'), mientras que la propiedad 'message' por lo general provee un breve mensaje que puede ser obtenido convirtiendo el error de object a string.</p>

<p>Si estás arrojando tus propias excepciones, en orden para tomar ventaja de estas propiedades (Como si tu bloque catch no discrimina entre tus propias excepciones y las excepciones del sistema), puedes usar el constructor de Error. Por ejemplo:</p>

<pre class="brush: js">function doSomethingErrorProne () {
  if (ourCodeMakesAMistake()) {
    throw (new Error('The message'));
  } else {
    doSomethingToGetAJavascriptError();
  }
}
....
try {
  doSomethingErrorProne();
}
catch (e) {
  console.log(e.name); // muestra 'Error'
  console.log(e.message); // muestra 'The message' o un error de JavaScript)
}</pre>

<h2 id="Promesas">Promesas</h2>

<p>A partir de ECMAScript 6, Javascript gana soporte para los objetos {{jsxref("Promise")}} que le permiten controlar el flujo de operaciones diferidas y asíncronas.</p>

<p>Un objeto <code>Promise</code> puede estar ubicado en estos estados:</p>

<ul>
 <li><em>pending</em>: Estado inicial, no terminada exitosamente o rechazada.</li>
 <li><em>fulfilled</em>: operación exitosa.</li>
 <li><em>rejected</em>: operación fallida.</li>
 <li><em>settled</em>: la Promesa ha sido exitosa o fallida, pero no está pendiente.</li>
</ul>

<p><img alt="" src="https://mdn.mozillademos.org/files/8633/promises.png" style="height: 297px; width: 801px;"></p>

<h3 id="Cargando_una_imagen_con_XHR">Cargando una imagen con XHR</h3>

<p>Un simple ejemplo del uso de <code>Promise</code> y <a href="/en-US/docs/Web/API/XMLHttpRequest">XMLHttpRequest</a> es cargar una imagen que está disponible en el repositorio <a href="https://github.com/mdn/promises-test/blob/gh-pages/index.html">promise-test</a> de MDN GitHub. Puedes <a href="http://mdn.github.io/promises-test/">verlo también en acción</a>. Cada paso es comentado y permite que sigas la arquitectura de la Promesa y XHR de cerca. Aquí está una versión sin comentar, mostrando el flujo de un <code>Promise</code> para que puedas tener una idea:</p>

<pre class="brush: js">function imgLoad(url) {
  return new Promise(function(resolve, reject) {
    var request = new XMLHttpRequest();
    request.open('GET', url);
    request.responseType = 'blob';
    request.onload = function() {
      if (request.status === 200) {
        resolve(request.response);
      } else {
        reject(Error('Image didn\'t load successfully; error code:' 
                     + request.statusText));
      }
    };
    request.onerror = function() {
      reject(Error('There was a network error.'));
    };
    request.send();
  });
}</pre>

<p>Para información más detallada, visitar {{jsxref("Promise")}} como página de referencia.</p>

<div>{{PreviousNext("Web/JavaScript/Guide/Grammar_and_types", "Web/JavaScript/Guide/Loops_and_iteration")}}</div>