<div>{{JSRef}}</div>

<p><span class="seoSummary">The <strong><code>Error</code></strong> constructor creates an error object.</span> Instances of <code>Error</code> objects are thrown when runtime errors occur. The <code>Error</code> object can also be used as a base object for user-defined exceptions. See below for standard built-in error types.</p>

<h2 id="Syntax">Syntax</h2>

<pre class="syntaxbox">new Error([<var>message</var>[, <var>fileName</var>[, <var>lineNumber</var>]]])</pre>

<h3 id="Parameters">Parameters</h3>

<dl>
 <dt><code><var>message</var></code>{{Optional_Inline}}</dt>
 <dd>A human-readable description of the error.</dd>
 <dt><code><var>fileName</var></code> {{Non-standard_Inline}}{{Optional_Inline}}</dt>
 <dd>The value for the <code><var>fileName</var></code> property on the created <code>Error</code> object. Defaults to the name of the file containing the code that called the <code>Error()</code> constructor.</dd>
 <dt><code><var>lineNumber</var></code> {{Non-standard_Inline}}{{Optional_Inline}}</dt>
 <dd>The value for the <code><var>lineNumber</var></code> property on the created <code>Error</code> object. Defaults to the line number containing the <code>Error()</code> constructor invocation.</dd>
</dl>

<h2 id="Description">Description</h2>

<p>Runtime errors result in new <code>Error</code> objects being created and thrown.</p>

<p>This page documents the use of the <code>Error</code> object itself and its use as a constructor function. For a list of properties and methods inherited by <code>Error</code> instances, see {{JSxRef("Error.prototype")}}.</p>

<h3 id="Used_as_a_function">Used as a function</h3>

<p>When <code>Error</code> is used like a function -- without {{JSxRef("Operators/new", "new")}}, it will return an <code>Error</code> object. Therefore, a mere call to <code>Error</code> will produce the same output that constructing an <code>Error</code> object via the <code>new</code> keyword would.</p>

<pre class="brush: js;">// this...
const x = Error('I was created using a function call!')

​​​​// ...has the same functionality as this.
const y = new Error('I was constructed via the "new" keyword!')
</pre>

<h3 id="Error_types">Error types</h3>

<p>Besides the generic <code>Error</code> constructor, there are seven other core error constructors in JavaScript. For client-side exceptions, see <a href="/en-US/docs/Web/JavaScript/Guide/Statements#Exception_handling_statements">Exception handling statements</a>.</p>

<dl>
 <dt>{{JSxRef("EvalError")}}</dt>
 <dd>Creates an instance representing an error that occurs regarding the global function {{JSxRef("eval", "eval()")}}.</dd>
 <dt>{{JSxRef("InternalError")}} {{Non-standard_Inline}}</dt>
 <dd>Creates an instance representing an error that occurs when an internal error in the JavaScript engine is thrown. E.g. "too much recursion".</dd>
 <dt>{{JSxRef("RangeError")}}</dt>
 <dd>Creates an instance representing an error that occurs when a numeric variable or parameter is outside of its valid range.</dd>
 <dt>{{JSxRef("ReferenceError")}}</dt>
 <dd>Creates an instance representing an error that occurs when de-referencing an invalid reference.</dd>
 <dt>{{JSxRef("SyntaxError")}}</dt>
 <dd>Creates an instance representing a syntax error that occurs while parsing code in {{JSxRef("eval", "eval()")}}.</dd>
 <dt>{{JSxRef("TypeError")}}</dt>
 <dd>Creates an instance representing an error that occurs when a variable or parameter is not of a valid type.</dd>
 <dt>{{JSxRef("URIError")}}</dt>
 <dd>Creates an instance representing an error that occurs when {{JSxRef("encodeURI", "encodeURI()")}} or {{JSxRef("decodeURI", "decodeURI()")}} are passed invalid parameters.</dd>
</dl>

<h2 id="Properties">Properties</h2>

<dl>
 <dt>{{JSxRef("Error.prototype")}}</dt>
 <dd>Allows the addition of properties to <code>Error</code> instances.</dd>
</dl>

<h2 id="Methods">Methods</h2>

<p>The global <code>Error</code> object contains no methods of its own, however, it does inherit some methods from the prototype chain.</p>

<h3 id="Non-standard_methods">Non-standard methods</h3>

<p>{{Non-standard_Header}}</p>

<dl>
 <dt>{{JSxRef("Error.captureStackTrace()")}} {{Non-standard_Inline}}</dt>
 <dd>A <strong>V8</strong> function that creates the {{JSxRef("Error.prototype.stack", "stack")}} property on an Error instance.</dd>
</dl>

<h2 id="Error_instances">Error instances</h2>

<div>{{page('/en-US/docs/JavaScript/Reference/Global_Objects/Error/prototype', 'Description')}}</div>

<h3 id="Properties_2">Properties</h3>

<div>{{page('/en-US/docs/JavaScript/Reference/Global_Objects/Error/prototype', 'Properties', '', '', 3)}}</div>

<h3 id="Methods_2">Methods</h3>

<div>{{page('/en-US/docs/JavaScript/Reference/Global_Objects/Error/prototype', 'Methods')}}</div>

<h2 id="Examples">Examples</h2>

<h3 id="Throwing_a_generic_error">Throwing a generic error</h3>

<p>Usually you create an <code>Error</code> object with the intention of raising it using the {{JSxRef("Statements/throw", "throw")}} keyword. You can handle the error using the {{JSxRef("Statements/try...catch", "try...catch")}} construct:</p>

<pre class="brush: js;">try {
  throw new Error('Whoops!')
} catch (e) {
  console.error(e.name + ': ' + e.message)
}
</pre>

<h3 id="Handling_a_specific_error">Handling a specific error</h3>

<p>You can choose to handle only specific error types by testing the error type with the error's {{JSxRef("Object.prototype.constructor", "constructor")}} property or, if you're writing for modern JavaScript engines, {{JSxRef("Operators/instanceof", "instanceof")}} keyword:</p>

<pre class="brush: js;">try {
  foo.bar()
} catch (e) {
  if (e instanceof EvalError) {
    console.error(e.name + ': ' + e.message)
  } else if (e instanceof RangeError) {
    console.error(e.name + ': ' + e.message)
  }
  // ... etc
}
</pre>

<h3 id="Custom_Error_Types">Custom Error Types</h3>

<p>You might want to define your own error types deriving from <code>Error</code> to be able to <code>throw new MyError()</code> and use <code>instanceof MyError</code> to check the kind of error in the exception handler.  This results in cleaner and more consistent error handling code. </p>

<p>See <a href="http://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript">"What's a good way to extend Error in JavaScript?"</a> on StackOverflow for an in-depth discussion.</p>

<h4 id="ES6_Custom_Error_Class">ES6 Custom Error Class</h4>

<div class="blockIndicator warning">
<p>Versions of Babel prior to 7 can handle <code>CustomError</code> class methods, but only when they are declared with <a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty">Object.defineProperty()</a>. Otherwise, old versions of Babel and other transpilers will not correctly handle the following code without <a href="https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend">additional configuration</a>.</p>
</div>

<div class="blockIndicator note">
<p>Some browsers include the <code>CustomError</code> constructor in the stack trace when using ES2015 classes.</p>
</div>

<pre class="brush: js">class CustomError extends Error {
  constructor(foo = 'bar', ...params) {
    // Pass remaining arguments (including vendor specific ones) to parent constructor
    super(...params)

    // Maintains proper stack trace for where our error was thrown (only available on V8)
    if (Error.captureStackTrace) {
      Error.captureStackTrace(this, CustomError)
    }

    this.name = 'CustomError'
    // Custom debugging information
    this.foo = foo
    this.date = new Date()
  }
}

try {
  throw new CustomError('baz', 'bazMessage')
} catch(e) {
  console.error(e.name)    //CustomError
  console.error(e.foo)     //baz
  console.error(e.message) //bazMessage
  console.error(e.stack)   //stacktrace
}</pre>

<h4 id="ES5_Custom_Error_Object">ES5 Custom Error Object</h4>

<div class="warning">
<p><strong>All</strong> browsers include the <code>CustomError</code> constructor in the stack trace when using a prototypal declaration.</p>
</div>

<pre class="brush: js">function CustomError(foo, message, fileName, lineNumber) {
  var instance = new Error(message, fileName, lineNumber);
  instance.name = 'CustomError';
  instance.foo = foo;
  Object.setPrototypeOf(instance, Object.getPrototypeOf(this));
  if (Error.captureStackTrace) {
    Error.captureStackTrace(instance, CustomError);
  }
  return instance;
}

CustomError.prototype = Object.create(Error.prototype, {
  constructor: {
    value: Error,
    enumerable: false,
    writable: true,
    configurable: true
  }
});

if (Object.setPrototypeOf){
  Object.setPrototypeOf(CustomError, Error);
} else {
  CustomError.__proto__ = Error;
}

try {
  throw new CustomError('baz', 'bazMessage');
} catch(e){
  console.error(e.name); //CustomError
  console.error(e.foo); //baz
  console.error(e.message); //bazMessage
}</pre>

<h2 id="Specifications">Specifications</h2>

<table class="standard-table">
 <thead>
  <tr>
   <th scope="col">Specification</th>
   <th scope="col">Status</th>
   <th scope="col">Comment</th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td>{{SpecName('ESDraft', '#sec-error-objects', 'Error')}}</td>
   <td>{{Spec2('ESDraft')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES2015', '#sec-error-objects', 'Error')}}</td>
   <td>{{Spec2('ES2015')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES5.1', '#sec-15.11', 'Error')}}</td>
   <td>{{Spec2('ES5.1')}}</td>
   <td></td>
  </tr>
  <tr>
   <td>{{SpecName('ES1')}}</td>
   <td>{{Spec2('ES1')}}</td>
   <td>Initial definition. Implemented in JavaScript 1.1.</td>
  </tr>
 </tbody>
</table>

<h2 id="Browser_compatibility">Browser compatibility</h2>

<div>
<div class="hidden">The compatibility table on this page is generated from structured data. If you'd like to contribute to the data, please check out <a href="https://github.com/mdn/browser-compat-data">https://github.com/mdn/browser-compat-data</a> and send us a pull request.</div>

<p>{{Compat("javascript.builtins.Error")}}</p>
</div>

<h2 id="See_also">See also</h2>

<ul>
 <li>{{JSxRef("Error.prototype")}}</li>
 <li>{{JSxRef("Statements/throw", "throw")}}</li>
 <li>{{JSxRef("Statements/try...catch", "try...catch")}}</li>
</ul>